name: otaku_movie_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  
  # Corrected RxDart package
  rxdart: ^0.28.0

  mobx: ^2.0.7
  flutter_mobx: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Required for generating MobX store code
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.5

flutter:
  uses-material-design: true

  # Add any assets or fonts here if needed in the future
  # assets:
  #   - images/a_dot_burr.jpeg
