name: otaku_movie_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  http: ^1.2.2

  rxdart: ^0.28.0

  mobx: ^2.0.7
  flutter_mobx: ^2.0.6
  flutter_localizations:
    sdk: flutter
    intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.1.11
  mobx_codegen: ^2.0.5

flutter:
  uses-material-design: true
